### ISSUE TITLE
to_denormalized_dataframe() creates weird MultiIndex column ('i', 'd')

### ISSUE THREAD

**Issue by lvsltz** [oruebel/ndx-icephys-meta#55] opened 2020-03-13 12:30 UTC
Tested on  branch add/spec_resp_elec_tables: https://github.com/oruebel/ndx-icephys-meta/commit/607e1ae41cd91f5a9021eb09fa54c256801e17f6

Unexpected column i,d appears as a column of the DataFrame generated with `to_denormalized_dataframe()`

![image](https://user-images.githubusercontent.com/6717189/76620249-0cbf0380-652d-11ea-8d64-0cdf21ba827d.png)

**How to reproduce:** run the [example code](https://github.com/oruebel/ndx-icephys-meta) including line
```
sweep_index = nwbfile.add_icephys_simultaneous_recording(recordings=[ir_index, ])
```
then compare
```
nwbfile.get_icephys_meta_parent_table().to_hierarchical_dataframe().columns
nwbfile.get_icephys_meta_parent_table().to_denormalized_dataframe().columns
```

**Comment by oruebel** [comment] 2020-03-13 15:59
@lvsltz thanks for the report. Yes, I noticed that too. I think the problem is that ``AlignedDynamicTable`` does not set the lable for the index column when it converts to a DataFrame. This bug is one of the reasons I had not merged the branch yet https://github.com/oruebel/ndx-icephys-meta/blob/607e1ae41cd91f5a9021eb09fa54c256801e17f6/src/pynwb/ndx_icephys_meta/icephys.py#L20
I'll work on this and the other TODO items on the branch next week.

**Comment by oruebel** [comment] 2020-03-18 20:51
This should be fixed now on https://github.com/oruebel/ndx-icephys-meta/pull/52

**Closed** 2020-03-19 12:42 UTC
